POST http://localhost:5005/api/v1/auth/register
Content-Type: application/json

{
    "username": "mod",
    "password": "password"
}

###
POST http://localhost:5005/api/v1/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "password"
}
###
GET http://localhost:5005/api/v1/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDAzYzhjZDNhMGUyODIwY2YxMzA1OWQiLCJpYXQiOjE2NzgxMTE4OTZ9.Cl4Nzao08DIY__TN8lPxIvl4MjV8k1x4Bt7n6-6OrL0

###
POST http://localhost:5005/api/v1/games
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDAzYzhjZDNhMGUyODIwY2YxMzA1OWQiLCJpYXQiOjE2Nzc5NzIxMzF9.ZJOlk9RKi1ShXpINfcTAJ_lEj6AfRhgVqI5fZNldKQk

{
    "gameName": "Liêndsd",
    "gameImage": "https://i.imgur.com/cXRItlH.jpg",
    "gameIcon" : "https://i.imgur.com/voDOiRT.jpg",
    "comingSoon": true
}

###
GET http://localhost:5005/api/v1/games

###
PUT http://localhost:5005/api/v1/games/6403d2af97a4c6bd78cc474b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDAzYzhjZDNhMGUyODIwY2YxMzA1OWQiLCJpYXQiOjE2Nzc5NzIxMzF9.ZJOlk9RKi1ShXpINfcTAJ_lEj6AfRhgVqI5fZNldKQk

{
    "gameName": "Liên Quân Mobile",
    "gameImage": "https://i.imgur.com/cXRItlH.jpg",
    "gameIcon" : "https://i.imgur.com/voDOiRT.jpg",
    "comingSoon": true
}
###
DELETE http://localhost:5005/api/v1/games/6403d89d1b4757444bf621ad
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDAzYzhjZDNhMGUyODIwY2YxMzA1OWQiLCJpYXQiOjE2Nzc5NzIxMzF9.ZJOlk9RKi1ShXpINfcTAJ_lEj6AfRhgVqI5fZNldKQk

### 
POST http://localhost:5005/api/v1/mod/6406647b95e6a2a9e5325d23
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDAzYzhjZDNhMGUyODIwY2YxMzA1OWQiLCJpYXQiOjE2Nzc5NzIxMzF9.ZJOlk9RKi1ShXpINfcTAJ_lEj6AfRhgVqI5fZNldKQk
